### ISSUE TITLE
Bug: Nuke Job Submission "You must specify a region." on submit

### ISSUE THREAD

**Issue by Ahuge** [aws-deadline/deadline-cloud#305]
### Expected Behaviour

The submitter should use the region that is configured in my Deadline Monitor profile

### Current Behaviour

It appears to try to use the default aws profile on the computer (*I think*) instead of the correct one.

The PR [#296](https://github.com/aws-deadline/deadline-cloud/pull/296) fixes this issue (and I have copy pasted the diff to confirm this). 
  
I think all we need is to do a new release with that code included.

### Reproduction Steps

Start a few Linux computer without any AWS config and set up and log into the Deadline Monitor.
Open up a nuke scene with the submitters installed and attempt to submit to your queue.

It throws an error saying "You must specify a region" deep down in the botocore.

### Code Snippet

`snip`
[submit_nuke_error.log](https://github.com/aws-deadline/deadline-cloud/files/15045956/submit_nuke_error.log)

**Comment by amarsjac** [comment]
Thanks for the bug report and for verifying the fix on your end. https://github.com/aws-deadline/deadline-cloud/pull/296 has been merged in and should be in the next scheduled release. I will leave this bug report open until that release is completed and we can verify the fix with that release.

**Comment by amarsjac** [comment]
Our release 0.48.0 34216d7  has been released and change https://github.com/aws-deadline/deadline-cloud/pull/296 is included in it. Thanks again for reporting this bug.
