### ISSUE TITLE
Feature request: Add datetime in DD/MM/YYYY format 

### ISSUE THREAD

**Issue by sahilrc** [aws-deadline/deadline-cloud#454]
### Describe the problem

Deadline Cloud task dashboard - date format is currently set as "62d 19h" - can we have an option to have "DD/MM/YYYY"?

<img width="1499" alt="AWS Deadline Cloud Dashboard UI Inquiry" src="https://github.com/user-attachments/assets/3e8c36fb-d63e-4028-aea6-ad7bbdc95e67">

### Proposed Solution

Change date format to DD/MM/YYYY.

### Example Use Cases

N/A

**Comment by rickrams** [comment]
It's somewhat hidden but if you tap on a time they will all switch to YYYY/MM/DD - definitely something we can make more obvious/configurable.
